vim.pack.add({ "https://github.com/folke/which-key.nvim" })

require("which-key").setup({
    preset = "helix",
    delay = 1000,
    sort = { "alphanum", "group" },
    plugins = { spelling = { enabled = false } },
    spec = {
        { "<leader>b", icon = "󰜘 " },
        { "<leader>c", icon = "󰅴 ", group = "[C]ode" },
        { "<leader>ca", icon = "󱐋 " },
        { "<leader>cc", hidden = true },
        { "<leader>cf", icon = "󰁨 " },
        { "<leader>cp", icon = "󰊪 " },
        { "<leader>e", icon = "󰙅 " },
        { "<leader>d", icon = " ", group = "[D]ebug" },
        { "<leader>db", icon = " " },
        { "<leader>dc", icon = " " },
        { "<leader>di", icon = "󰆹 " },
        { "<leader>do", icon = "󰆷 " },
        { "<leader>dO", icon = "󰆸 " },
        { "<leader>f", icon = "󰍉 ", group = "[F]ind" },
        { "<leader>fd", icon = "󰈸 " },
        { "<leader>ff", icon = "󰈔 " },
        { "<leader>fg", icon = "󰦨 " },
        { "<leader>fh", icon = "󰋖 " },
        { "<leader>fk", icon = "󰌌 " },
        { "<leader>fs", icon = " " },
        { "<leader>ft", icon = "󰄲 " },
        { "<leader>fu", icon = "󰕌 " },
        { "<leader>g", icon = "󱞫 ", group = "[G]o to" },
        { "<leader>gb", icon = "󱞡 " },
        { "<leader>gd", icon = " " },
        { "<leader>gg", icon = "󰊤 " },
        { "<leader>gr", icon = " " },
        { "<leader>h", icon = "󱡅 " },
        { "<leader>l", icon = "󰒲 ", group = "[L]azy" },
        { "<leader>lg", icon = "󰊢 " },
        { "<leader>lm", icon = "󰏓 " },
        { "<leader>m", icon = "󱡅 " },
        { "<leader>q", icon = " " },
        { "<leader>r", icon = "󰑕 " },
        { "<leader>t", icon = "󰈸 " },
        { "<leader>$", icon = " " },
        { "<leader>1", hidden = true },
        { "<leader>2", hidden = true },
        { "<leader>3", hidden = true },
        { "<leader>4", hidden = true },
        { "<leader>5", hidden = true },
        { "<leader>6", hidden = true },
        { "<leader>7", hidden = true },
        { "<leader>8", hidden = true },
        { "<leader>9", hidden = true },
    },
})
